### ISSUE TITLE
Fix GeoIP tests

### ISSUE THREAD

**Issue by orf** [orf/django-docker-box#19]
The GeoIP tests fail: https://travis-ci.com/orf/django-docker-box/jobs/153405139. I've disabled them in 4d2371e4a14e9a381b69fc38cd79807030a32c8a for now.

```
======================================================================
FAIL: test04_city (gis_tests.test_geoip2.GeoIPTest)
GeoIP city querying methods.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.5/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/local/lib/python3.5/unittest/mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "/tests/django/tests/gis_tests/test_geoip2.py", line 138, in test04_city
    self.assertAlmostEqual(lat, tup[1], 4)
  File "/usr/local/lib/python3.5/unittest/case.py", line 877, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 29.7079 != 29.7041 within 4 places
======================================================================
FAIL: test05_unicode_response (gis_tests.test_geoip2.GeoIPTest)
GeoIP strings should be properly encoded (#16553).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.5/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/local/lib/python3.5/unittest/mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "/tests/django/tests/gis_tests/test_geoip2.py", line 146, in test05_unicode_response
    self.assertEqual('Niğde', d['city'])
  File "/usr/local/lib/python3.5/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.5/unittest/case.py", line 1202, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/lib/python3.5/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: 'Niğde' != 'Lomma'
- Niğde
+ Lomma
```

This could be due to the up to date maxmind database we are using. They do look a bit flakey.

**Comment by timgraham** [comment]
Yes, if you check `git log tests/gis_tests/test_geoip2.py`, you'll see many "Fixed a test failure with the latest GeoIP2 database." commits. I avoid routinely updating the GeoIP database on Jenkins for that reason. It seems that contributors rarely go through the effort of running the tests as nobody as ever complained.
